### ISSUE TITLE
check changes in `remark-lint` 6.0.0

### ISSUE THREAD

**Issue by whizark** [whizark/remark-preset#1]
* [remark-lint/rules.md at master · wooorm/remark-lint](https://github.com/wooorm/remark-lint/blob/master/doc/rules.md)

**Comment by wooorm** [comment]
Hi! Could you let me know if you’ve got any further questions re updating? Either below or on [Gitter](https://gitter.im/wooorm/remark)!

**Comment by whizark** [comment]
Hi, thank you for your active development and your information about Gitter!
I'll post/open a message/issue if I have any questions or notice any issues after I check new package structure :smiley:

**Comment by wooorm** [comment]
Alright, great! 👍
